site_name: iirspy
repo_url: https://github.com/cjtu/iirspy
site_url: https://cjtu.github.io/iirspy
site_description: Handling and correcting Chandrayaan-2 IIRS data in Python.
site_author: Christian J. Tai Udovicic
edit_uri: edit/main/docs/
repo_name: cjtu/iirspy
copyright: Maintained by <a href="https://cjtu.com">cjtu</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/iirspy"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cjtu/iirspy
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/iirspy

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
